# Generated by Django 4.1 on 2022-10-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_food_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='detail',
        ),
    ]
