# Generated by Django 4.1 on 2022-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_food_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image_url',
        ),
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
