# Generated by Django 4.1 on 2022-11-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_food_image_url_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.CharField(default='h', max_length=2083),
            preserve_default=False,
        ),
    ]
